// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBtBX-Zhh5Iv363Mwo3X9LvCdVGTNS25Q',
    appId: '1:416792605770:web:05cb53c1eb19394385e2b3',
    messagingSenderId: '416792605770',
    projectId: 'mynotes-7175e',
    authDomain: 'mynotes-7175e.firebaseapp.com',
    storageBucket: 'mynotes-7175e.appspot.com',
    measurementId: 'G-P3CWSHLJK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZRk8awiDFsW33nKqqG0GME8PNQfYQMsg',
    appId: '1:416792605770:android:cf41f66e5971118385e2b3',
    messagingSenderId: '416792605770',
    projectId: 'mynotes-7175e',
    storageBucket: 'mynotes-7175e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIGhh7d6MFYcIbfbHyhMHj76A3rJ1smGc',
    appId: '1:416792605770:ios:a67e931dc6c3acdf85e2b3',
    messagingSenderId: '416792605770',
    projectId: 'mynotes-7175e',
    storageBucket: 'mynotes-7175e.appspot.com',
    iosClientId: '416792605770-e1lv7jruo2a9gledbkc0qqgb0jmraqgm.apps.googleusercontent.com',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIGhh7d6MFYcIbfbHyhMHj76A3rJ1smGc',
    appId: '1:416792605770:ios:5e5399598d75731385e2b3',
    messagingSenderId: '416792605770',
    projectId: 'mynotes-7175e',
    storageBucket: 'mynotes-7175e.appspot.com',
    iosClientId: '416792605770-ivr54ounn3i6ng51ae3cofna3o2k6d1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.testproject.RunnerTests',
  );
}
